### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ivantehassassin** [Wimberton/OriginPalia#24]
Crashing when changing areas

**Comment by ivantehassassin** [comment]
change dx12 to dx11 and it seems i dont get so many crashes

**Comment by ivantehassassin** [comment]
where can i find the changelog?

**Comment by Wimberton** [comment]
> where can i find the changelog?

Changelogs are found [in the Wiki section](https://github.com/Wimberton/OriginPalia/wiki)
We're currently investigating a small crashing issue that happens if you teleport to a listed location and leave the current world too quickly. It's due to some client garbage cleanup that doesn't seem to function correctly (most likely the game devs shitty coding)
