### ISSUE TITLE
sus

### ISSUE THREAD

**Issue by Tinn142** [Wimberton/OriginPalia#8]
https://www.virustotal.com/gui/file/73bd789d07e3d70a591f74419cdffd22d98e700d9b322bc149acc54271ac635a/detection

That seems a bit sus for me tbh

**Comment by Nekomimis** [comment]
It's the same for almost every cheat DLLs you use. Balls & T4bby had the same results.

**Comment by Wimberton** [comment]
> Those results aren't coming from the hack itself, its from the new loader Wim included, which it downloads and injects to the game. I also don't much about the new loader to talk about it.

The loader may be showing this due to the connections it makes to get the currently updated DLL and inject.
I use KeyAuth to intialized and store the DLL and data into the cloud so you can login and inject using the automatic latest edition.

I will fix the loader now. Seems it's having issues. I had to remove some licensing code I've used in the past, so that's causing the bytes error upon invalid auth.

**Comment by Wimberton** [comment]
> https://www.virustotal.com/gui/file/73bd789d07e3d70a591f74419cdffd22d98e700d9b322bc149acc54271ac635a/detection
> 
> That seems a bit sus for me tbh

The code is open. If you find the DLL or loader to be sus, you're more than willing to compile, review, and use your own loader files.

**Comment by Wimberton** [comment]
> https://www.virustotal.com/gui/file/73bd789d07e3d70a591f74419cdffd22d98e700d9b322bc149acc54271ac635a/detection
> 
> That seems a bit sus for me tbh

The code is open. If you find the DLL or loader to be sus, you're more than willing to compile, review, and use your own loader files. Or not at all, it's completely up to you.
